version: "3.7"

x-service-volumes: &service-volumes
    - ./:/app/:rw,cached

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        env_file: 
            - ./config/db.env
        volumes:
            - db-data:/var/lib/postgressql/data

    website:
        image: hackershack-website-tutorial:latest
        command: python manage.py runserver 0.0.0.0:8000
        volumes: *service-volumes
        env_file: 
            - ./config/app.env
            - ./config/db.env
        depends_on: 
            - db_migrate
        ports:
            - "8000:8000"

    db_migrate:
        image: hackershack-website-tutorial:latest
        command: python manage.py migrate
        volumes: *service-volumes
        env_file: 
            - ./config/app.env
            - ./config/db.env
        depends_on: 
            - postgres
        
volumes:
    db-data: